# Generated by Django 4.2 on 2023-04-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='duration',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='rating',
            field=models.FloatField(default='0'),
        ),
    ]
