# Generated by Django 4.2 on 2023-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_moviedata_duration_moviedata_total_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='genre',
            field=models.CharField(default='drama', max_length=200),
        ),
    ]
